---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: save-file-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: moodle-utils-sc
  resources:
    requests:
      storage: 1Gi
