---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-service
  name: server-service
  namespace: moodle-utils-ns
spec:
  ports:
    - name: "http"
      port: 443
      targetPort: 8080
  selector:
    app: server
  type: LoadBalancer
status:
  loadBalancer: {}
